/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js on `next dev` / `next build`.
// It is safe to leave as-is; Next.js will overwrite it.